version: '2'
volumes:
  sonar-db-data:
services:
  sonar-db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
      - ./dbconf:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - build
  sonarqube:
    image: sonarqube:alpine
    links:
      - sonar-db:db
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://db/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&createDatabaseIfNotExist=true
      - SONARQUBE_JDBC_USERNAME=root
      - SONARQUBE_JDBC_PASSWORD=123456
    volumes:
      # - ./snrconf:/opt/sonarqube/conf
      # - ./snrdata:/opt/sonarqube/data
      - ./snrlogs:/opt/sonarqube/logs
    volumes_from:
      - plugins
    restart: "no"
    networks:
      - build
  plugins:
    build: plugins
    restart: "no"
networks:
  build:
    driver: bridge    
